const SPECIES = [
  {
    id: 'largemouth-bass',
    name: 'Largemouth Bass',
    scientific: 'Micropterus salmoides',
    aka: ['Bigmouth', 'Bucketmouth', 'Hawg'],
    category: 'bass',
    difficulty: 2,
    typicalSize: '1–5 lbs',
    stateRecord: '22 lb 4 oz',
    fight: 'Strong',
    taste: 'Good',
    description: 'The most popular game fish in Georgia and the king of freshwater fishing. Found in virtually every pond, lake, and slow-moving river in the Portal area.',
    habitat: 'Ponds, lakes, and slow-moving rivers. Always near cover — fallen trees, lily pads, dock pilings, and brush piles.',
    waterTypes: ['pond', 'lake', 'river'],
    bestSeasons: ['spring', 'fall'],
    bestTimes: ['Dawn', 'Dusk'],
    activeMonths: [1,2,3,4,5,6,7,8,9,10,11,12],
    peakMonths: [3,4,5,10],
    diet: 'Minnows, crawfish, frogs, insects, and smaller fish.',
    baits: {
      live: ['Shiners', 'Nightcrawlers', 'Crawfish'],
      artificial: ['Plastic worms (Texas rig)', 'Spinnerbaits', 'Topwater frogs', 'Crankbaits', 'Jigs'],
    },
    tips: [
      'Cast tight to cover — fallen trees, lily pads, dock pilings are where bass hide',
      'In summer, fish deeper during midday and shallow at dawn and dusk',
      'Topwater lures in low light produce explosive strikes',
      'Spring spawning bass are aggressive but practice catch-and-release on bedding fish',
    ],
    funFact: 'The world record largemouth bass (22 lb 4 oz) was caught right here in Georgia at Montgomery Lake in 1932 — a record that stood alone for over 70 years.',
    regulations: { minSize: '12" on public waters', dailyLimit: '10/day (combined bass)' },
  },
  {
    id: 'spotted-bass',
    name: 'Spotted Bass',
    scientific: 'Micropterus punctulatus',
    aka: ['Kentucky Bass', 'Spot'],
    category: 'bass',
    difficulty: 2,
    typicalSize: '1–3 lbs',
    stateRecord: '8 lb 15 oz',
    fight: 'Strong',
    taste: 'Good',
    description: 'A scrappy cousin of the largemouth that prefers moving water. Pound for pound, one of the hardest fighting bass you\'ll encounter.',
    habitat: 'Rivers and streams with moderate current. Rocky banks, bluffs, and current breaks.',
    waterTypes: ['river', 'creek'],
    bestSeasons: ['spring', 'fall'],
    bestTimes: ['Morning', 'Evening'],
    activeMonths: [1,2,3,4,5,6,7,8,9,10,11,12],
    peakMonths: [3,4,10,11],
    diet: 'Crawfish, minnows, and aquatic insects.',
    baits: {
      live: ['Crawfish', 'Minnows'],
      artificial: ['Crawfish imitations', 'Small jerkbaits', 'Jigs', 'Finesse worms'],
    },
    tips: [
      'More current-oriented than largemouth — look for eddies and current breaks',
      'Smaller mouth than largemouth, so downsize your baits',
      'Crawfish-colored lures are king for spotted bass',
      'Often found in the same water as largemouth but holding in slightly different spots near current',
    ],
    funFact: 'Spotted bass fight harder pound-for-pound than their largemouth cousins and are sometimes called "Kentucky bass" after the state where they were first scientifically described.',
    regulations: { minSize: '12"', dailyLimit: '10/day (combined with largemouth)' },
  },
  {
    id: 'channel-catfish',
    name: 'Channel Catfish',
    scientific: 'Ictalurus punctatus',
    aka: ['Channel Cat', 'Spotted Cat'],
    category: 'catfish',
    difficulty: 1,
    typicalSize: '1–5 lbs',
    stateRecord: '44 lb 12 oz',
    fight: 'Moderate',
    taste: 'Excellent',
    description: 'The most common catfish in Georgia and one of the easiest fish to catch. Great eating and found in almost every body of water.',
    habitat: 'Rivers, ponds, and lakes. Prefers deeper holes with some current, but will live just about anywhere.',
    waterTypes: ['river', 'pond', 'lake'],
    bestSeasons: ['spring', 'summer'],
    bestTimes: ['Evening', 'Night'],
    activeMonths: [3,4,5,6,7,8,9,10,11],
    peakMonths: [5,6,7,8],
    diet: 'Omnivorous — insects, crawfish, fish, plants, and just about anything else.',
    baits: {
      live: ['Nightcrawlers', 'Crawfish', 'Live minnows'],
      artificial: [],
      prepared: ['Chicken liver', 'Punch bait (stinkbait)', 'Doughbait', 'Hot dogs', 'Shrimp'],
    },
    tips: [
      'Fish on the bottom using a slip sinker rig',
      'Chicken liver is the classic — wrap it with thread or use a bait holder hook to keep it on',
      'Circle hooks give better hookup rates and make unhooking easier',
      'After a rain, fish the edges where muddy water meets clear — catfish follow the scent trail',
    ],
    funFact: 'Channel catfish can taste with their entire body — they have over 100,000 taste buds covering their skin, whiskers, and fins. Their whole body is basically a tongue.',
    regulations: { minSize: 'None', dailyLimit: '50/day' },
  },
  {
    id: 'blue-catfish',
    name: 'Blue Catfish',
    scientific: 'Ictalurus furcatus',
    aka: ['Blue Cat', 'Humpback Blue'],
    category: 'catfish',
    difficulty: 2,
    typicalSize: '5–20 lbs',
    stateRecord: '110 lb',
    fight: 'Powerful',
    taste: 'Excellent',
    description: 'The largest catfish species in North America. Can grow to enormous sizes and feeds aggressively in cold water when other fish have shut down.',
    habitat: 'Large rivers with current. Deep channel bends, holes below dams, and main river ledges.',
    waterTypes: ['river'],
    bestSeasons: ['fall', 'winter'],
    bestTimes: ['All day', 'Best at night'],
    activeMonths: [1,2,3,4,5,6,7,8,9,10,11,12],
    peakMonths: [10,11,12,1,2],
    diet: 'Shad, herring, and other fish. Opportunistic predator.',
    baits: {
      live: ['Live shad', 'Large minnows', 'Live bluegill (where legal)'],
      artificial: ['Large swimbaits (occasionally)'],
      prepared: ['Cut shad', 'Cut skipjack herring', 'Chicken breast'],
    },
    tips: [
      'They feed aggressively in cold water when bass and other fish slow down — great winter fishing',
      'Fresh cut shad in 1-inch chunks is hard to beat',
      'Use heavy tackle — 30 to 50 lb test line minimum for big blues',
      'Fish current breaks — below points, in channel bends, near drop-offs',
    ],
    funFact: 'Blue catfish can live over 20 years and the Georgia state record is 110 pounds. They\'re the largest species of catfish in North America.',
    regulations: { minSize: 'None', dailyLimit: '50/day' },
  },
  {
    id: 'flathead-catfish',
    name: 'Flathead Catfish',
    scientific: 'Pylodictis olivaris',
    aka: ['Yellow Cat', 'Shovelhead', 'Mud Cat'],
    category: 'catfish',
    difficulty: 3,
    typicalSize: '5–20 lbs',
    stateRecord: '83 lb',
    fight: 'Powerful',
    taste: 'Excellent',
    description: 'A solitary ambush predator and one of the hardest-fighting freshwater fish. Many anglers consider flatheads the best-tasting catfish. Requires patience and live bait.',
    habitat: 'Rivers and large creeks. Deep holes, logjams, undercut banks, and underwater caves.',
    waterTypes: ['river'],
    bestSeasons: ['summer'],
    bestTimes: ['Night'],
    activeMonths: [4,5,6,7,8,9,10],
    peakMonths: [6,7,8],
    diet: 'Almost exclusively live fish — bluegill, shad, and other fish.',
    baits: {
      live: ['Live bluegill', 'Live shad', 'Large live minnows'],
      artificial: [],
      prepared: [],
    },
    tips: [
      'Flatheads want LIVE bait — they rarely eat anything dead',
      'Fish deep river holes near logjams after dark for the best results',
      'Use a heavy rod holder or secure your rod — a big flathead will pull it in the water',
      'Be patient — you might only get one or two bites per night, but they\'ll be worth it',
    ],
    funFact: 'Flathead catfish are ambush predators that hide in underwater caves and logjams during the day, then come out to hunt at night like freshwater lions.',
    regulations: { minSize: 'None', dailyLimit: '50/day' },
  },
  {
    id: 'bullhead-catfish',
    name: 'Bullhead Catfish',
    scientific: 'Ameiurus spp.',
    aka: ['Mudcat', 'Horned Pout', 'Polliwog'],
    category: 'catfish',
    difficulty: 1,
    typicalSize: '0.5–2 lbs',
    stateRecord: '~5 lb',
    fight: 'Mild',
    taste: 'Good',
    description: 'The easiest catfish to catch. Found in virtually every pond and ditch in the area. Excellent beginner fish — they bite almost anything.',
    habitat: 'Ponds, slow creeks, and ditches. Muddy bottoms and weedy areas. They thrive where other fish struggle.',
    waterTypes: ['pond', 'creek', 'ditch'],
    bestSeasons: ['spring', 'summer'],
    bestTimes: ['Evening', 'Night'],
    activeMonths: [3,4,5,6,7,8,9,10],
    peakMonths: [5,6,7],
    diet: 'Worms, insects, snails, small fish — they eat just about anything.',
    baits: {
      live: ['Nightcrawlers (half a worm is plenty)', 'Red wigglers'],
      artificial: [],
      prepared: ['Hot dogs', 'Bread balls', 'Kernel corn', 'Chicken liver'],
    },
    tips: [
      'Great beginner fish — they bite almost anything on the bottom',
      'Watch out for sharp spines on their pectoral and dorsal fins',
      'To hold safely, grip firmly behind the head with the spines between your fingers',
      'If there\'s a muddy-bottomed pond nearby, there are probably bullheads in it',
    ],
    funFact: 'Bullheads can survive in water with oxygen levels so low it would kill most other fish. They can even gulp air at the surface and absorb oxygen through a modified swim bladder.',
    regulations: { minSize: 'None', dailyLimit: 'None' },
  },
  {
    id: 'bluegill',
    name: 'Bluegill',
    scientific: 'Lepomis macrochirus',
    aka: ['Bream', 'Sun Perch', 'Coppernose'],
    category: 'panfish',
    difficulty: 1,
    typicalSize: '0.25–1 lb',
    stateRecord: '2 lb 12 oz',
    fight: 'Moderate',
    taste: 'Excellent',
    description: 'The most common fish in SE Georgia and one of the best-tasting freshwater fish there is. Found everywhere. On ultralight tackle, they put up a surprisingly fun fight.',
    habitat: 'Everywhere — ponds, lakes, rivers, creeks. Near structure and vegetation in shallow water.',
    waterTypes: ['pond', 'lake', 'river', 'creek'],
    bestSeasons: ['spring', 'summer'],
    bestTimes: ['Morning', 'Evening'],
    activeMonths: [3,4,5,6,7,8,9,10,11],
    peakMonths: [5,6,7],
    diet: 'Insects, worms, small crustaceans, and larvae.',
    baits: {
      live: ['Crickets', 'Red wigglers', 'Waxworms'],
      artificial: ['Small inline spinners (Rooster Tails)', 'Tiny jigs (1/64–1/32 oz)', 'Small poppers'],
      prepared: ['Bread balls', 'Kernel corn'],
    },
    tips: [
      'In late spring, look for circular beds in shallow sandy areas — dozens of bluegill will be spawning',
      'Crickets under a small bobber is the classic setup and still one of the best',
      'Use ultralight tackle (4–6 lb line) — it makes them way more fun to catch',
      'Size 8–10 hooks are ideal. Bigger hooks mean missed bites.',
    ],
    funFact: 'Male bluegill are dedicated fathers — they build the nest, guard the eggs, and fan them with their fins to keep them clean and oxygenated until they hatch.',
    regulations: { minSize: 'None', dailyLimit: '50/day' },
  },
  {
    id: 'redear-sunfish',
    name: 'Redear Sunfish',
    scientific: 'Lepomis microlophus',
    aka: ['Shellcracker', 'Cherry Gill', 'Georgia Bream'],
    category: 'panfish',
    difficulty: 2,
    typicalSize: '0.5–1.5 lbs',
    stateRecord: '4 lb 4 oz',
    fight: 'Moderate',
    taste: 'Excellent',
    description: 'Bigger than bluegill on average and prized for their size and taste. Called "shellcrackers" because they specialize in crushing snail shells with their throat teeth.',
    habitat: 'Ponds and lakes with sandy or gravelly bottoms. Usually found deeper than bluegill.',
    waterTypes: ['pond', 'lake'],
    bestSeasons: ['spring'],
    bestTimes: ['Morning'],
    activeMonths: [3,4,5,6,7,8,9,10],
    peakMonths: [4,5],
    diet: 'Snails, mussels, larvae — they specialize in crushing hard-shelled prey.',
    baits: {
      live: ['Red wigglers', 'Nightcrawlers (half)', 'Crickets'],
      artificial: ['Small jigs tipped with a piece of worm'],
    },
    tips: [
      'They bed slightly before bluegill in spring — target them first',
      'Fish near the bottom in sandy or gravelly areas, not on the surface like bluegill',
      'They bite more delicately than bluegill — watch your line closely for subtle twitches',
      'They grow bigger than bluegill on average, so they\'re worth targeting specifically',
    ],
    funFact: 'Called "shellcrackers" because they have special pharyngeal teeth in their throat that crush snail shells. You can sometimes hear the crunching if you listen closely to the water.',
    regulations: { minSize: 'None', dailyLimit: '50/day' },
  },
  {
    id: 'redbreast-sunfish',
    name: 'Redbreast Sunfish',
    scientific: 'Lepomis auritus',
    aka: ['River Bream', 'Longear', 'Yellowbelly'],
    category: 'panfish',
    difficulty: 1,
    typicalSize: '0.25–0.75 lb',
    stateRecord: '1 lb 12 oz',
    fight: 'Moderate',
    taste: 'Excellent',
    description: 'A beautiful, colorful sunfish that loves creeks and rivers with current. Classic Georgia creek fishing targets these.',
    habitat: 'Creeks and small rivers with sandy bottoms and flowing water. Pools behind rocks and near undercut banks.',
    waterTypes: ['creek', 'river'],
    bestSeasons: ['spring', 'summer'],
    bestTimes: ['Morning', 'Evening'],
    activeMonths: [3,4,5,6,7,8,9,10],
    peakMonths: [5,6,7],
    diet: 'Insects, larvae, small crawfish.',
    baits: {
      live: ['Crickets', 'Red wigglers', 'Catalpa worms'],
      artificial: ['Small inline spinners (Rooster Tails)', 'Tiny crankbaits'],
    },
    tips: [
      'Wade small creeks and cast upstream — this is classic Georgia creek fishing at its best',
      'Look for them in pools behind rocks and near undercut banks',
      'They\'re more colorful than bluegill with a vivid orange-red breast',
      'Light spinning gear or fly fishing tackle makes this the most fun',
    ],
    funFact: 'Male redbreast sunfish have an elongated dark ear flap that can extend over an inch long — no other sunfish in Georgia has one that big.',
    regulations: { minSize: 'None', dailyLimit: '50/day' },
  },
  {
    id: 'warmouth',
    name: 'Warmouth',
    scientific: 'Lepomis gulosus',
    aka: ['Goggle-Eye', 'Red-Eyed Bream', 'Stumpknocker'],
    category: 'panfish',
    difficulty: 1,
    typicalSize: '0.25–0.75 lb',
    stateRecord: '2 lb 5 oz',
    fight: 'Moderate',
    taste: 'Good',
    description: 'A thick-bodied, aggressive sunfish that thrives in dark, swampy water where other panfish don\'t. Has distinctive red eyes.',
    habitat: 'Swampy areas, weedy ponds, slow creeks with muddy bottoms. Near cypress trees and in backwater areas.',
    waterTypes: ['pond', 'creek', 'swamp'],
    bestSeasons: ['spring', 'summer'],
    bestTimes: ['Morning'],
    activeMonths: [3,4,5,6,7,8,9,10],
    peakMonths: [5,6],
    diet: 'Insects, small crawfish, small fish. More aggressive feeders than most sunfish.',
    baits: {
      live: ['Crickets', 'Worms'],
      artificial: ['Small jigs', 'Tiny crankbaits'],
    },
    tips: [
      'Found in darker, muddier water than bluegill — they love swampy spots',
      'Larger mouth for their size than other sunfish, so they\'re more aggressive biters',
      'Look for them around cypress trees and in swampy backwaters',
      'They have red eyes — that\'s how you tell them apart from similar-looking rock bass',
    ],
    funFact: 'Warmouth have red eyes that help them see in murky, stained water — they\'re perfectly built for the dark, swampy habitats that other sunfish avoid.',
    regulations: { minSize: 'None', dailyLimit: '50/day' },
  },
  {
    id: 'crappie',
    name: 'Crappie',
    scientific: 'Pomoxis spp.',
    aka: ['Speckled Perch', 'Specks', 'Papermouth', 'Sac-a-lait'],
    category: 'panfish',
    difficulty: 2,
    typicalSize: '0.5–2 lbs',
    stateRecord: '4 lb 8 oz',
    fight: 'Mild',
    taste: 'Excellent',
    description: 'One of the best-eating freshwater fish, period. Both black and white crappie are found in the area. They school up in winter and spring making for fast action when you find them.',
    habitat: 'Lakes, rivers, and larger ponds. Around brush piles, standing timber, bridge pilings, and docks.',
    waterTypes: ['lake', 'river', 'pond'],
    bestSeasons: ['winter', 'spring'],
    bestTimes: ['Dawn', 'Overcast days'],
    activeMonths: [1,2,3,4,5,6,7,8,9,10,11,12],
    peakMonths: [2,3,4],
    diet: 'Small minnows, insects, tiny shad.',
    baits: {
      live: ['Live minnows (the #1 bait)', 'Small shiners'],
      artificial: ['Tube jigs (1/16 oz)', 'Curly tail grubs', 'Small crappie jigs', 'Spider jigs'],
    },
    tips: [
      'Late winter and early spring pre-spawn is the best time — they stack up in staging areas',
      'Fish brush piles and standing timber, varying your depth until you find the school',
      'When you catch one, keep casting to the same spot — crappie school up tight',
      'Their mouths are paper-thin so don\'t set the hook hard — a gentle lift is all you need',
    ],
    funFact: 'Called "papermouth" because their mouths tear easily — if you jerk the hook too hard, it rips right through. Finesse is the name of the game.',
    regulations: { minSize: '8" (most waters)', dailyLimit: '30/day' },
  },
  {
    id: 'chain-pickerel',
    name: 'Chain Pickerel',
    scientific: 'Esox niger',
    aka: ['Jack', 'Jackfish', 'Southern Pike', 'Pike'],
    category: 'predator',
    difficulty: 2,
    typicalSize: '1–3 lbs',
    stateRecord: '8 lb 12 oz',
    fight: 'Strong',
    taste: 'Fair',
    description: 'A toothy, aggressive predator and the southernmost member of the pike family. Explosive strikes and acrobatic fights. Bony but edible if you know how to fillet around the Y-bones.',
    habitat: 'Weedy ponds, swampy areas, and creek backwaters. Near thick vegetation.',
    waterTypes: ['pond', 'creek', 'swamp'],
    bestSeasons: ['fall', 'winter'],
    bestTimes: ['Morning'],
    activeMonths: [1,2,3,4,5,6,7,8,9,10,11,12],
    peakMonths: [10,11,12,1,2],
    diet: 'Fish, frogs, mice — anything that moves and fits in their mouth.',
    baits: {
      live: ['Live minnows', 'Small shiners'],
      artificial: ['Spinnerbaits', 'Weedless spoons (Johnson Silver Minnow)', 'Small swimbaits', 'Topwater plugs'],
    },
    tips: [
      'Use a short wire or heavy fluorocarbon leader — their teeth will cut regular line',
      'Cast parallel to weed edges and retrieve steadily',
      'They\'re cold-water hunters, most active when bass have slowed down for winter',
      'Handle with care — they have razor-sharp teeth and thrash hard when caught',
    ],
    funFact: 'Chain pickerel are Georgia\'s version of a northern pike. They get their name from the chain-link fence pattern on their sides.',
    regulations: { minSize: 'None', dailyLimit: 'None' },
  },
  {
    id: 'bowfin',
    name: 'Bowfin',
    scientific: 'Amia calva',
    aka: ['Mudfish', 'Cypress Trout', 'Dogfish', 'Grinnel'],
    category: 'predator',
    difficulty: 2,
    typicalSize: '2–8 lbs',
    stateRecord: '16 lb',
    fight: 'Powerful',
    taste: 'Catch-and-Release',
    description: 'A prehistoric survivor and one of the hardest-fighting freshwater fish you\'ll ever hook. Bowfin have been around since the dinosaurs and fight like it. Best released — the meat gets mushy quickly.',
    habitat: 'Swampy backwaters, weedy ponds, slow rivers. Areas with low oxygen that other fish avoid.',
    waterTypes: ['swamp', 'pond', 'river'],
    bestSeasons: ['spring', 'summer'],
    bestTimes: ['Morning', 'Evening'],
    activeMonths: [3,4,5,6,7,8,9,10],
    peakMonths: [4,5,6],
    diet: 'Fish, crawfish, frogs, insects.',
    baits: {
      live: ['Nightcrawlers', 'Crawfish', 'Live minnows'],
      artificial: ['Spinnerbaits', 'Soft plastics', 'Topwater plugs'],
      prepared: ['Cut bait'],
    },
    tips: [
      'Use heavy line — 17+ lb test minimum. They are incredibly strong fighters',
      'Look for them in swampy areas near cypress trees',
      'They can breathe air, so you\'ll sometimes see them gulp at the surface',
      'Often caught while bass fishing, but they\'re worth targeting on purpose for the fight alone',
    ],
    funFact: 'Bowfin are living fossils — they\'ve existed for over 150 million years. They can breathe air using a swim bladder that works like a primitive lung, surviving in water that would kill any other fish.',
    regulations: { minSize: 'None', dailyLimit: 'None' },
  },
  {
    id: 'longnose-gar',
    name: 'Longnose Gar',
    scientific: 'Lepisosteus osseus',
    aka: ['Gar', 'Garfish', 'Gar Pike', 'Needlenose'],
    category: 'predator',
    difficulty: 3,
    typicalSize: '3–10 lbs',
    stateRecord: '41 lb',
    fight: 'Strong',
    taste: 'Fair',
    description: 'Another prehistoric fish with a long, toothy snout and diamond-hard armor scales. They surface to gulp air and are notoriously hard to hook using conventional methods — but there are tricks.',
    habitat: 'Slow rivers, backwaters, and lakes. Often seen cruising near the surface.',
    waterTypes: ['river', 'lake', 'swamp'],
    bestSeasons: ['summer'],
    bestTimes: ['Midday'],
    activeMonths: [4,5,6,7,8,9,10],
    peakMonths: [6,7,8],
    diet: 'Fish — primarily minnows and shad.',
    baits: {
      live: ['Live minnows', 'Small fish'],
      artificial: ['Rope lures (nylon rope frayed at the end)'],
      prepared: ['Cut bait on treble hooks'],
    },
    tips: [
      'Traditional hooks often won\'t work — their bony snout is nearly impossible to penetrate',
      'Try a rope lure: unravel nylon rope into a fuzzy tangle. Gar teeth get tangled in the fibers',
      'Let them run with the bait for 10–15 seconds before setting the hook',
      'You can sight-fish for them when they surface to gulp air at midday',
    ],
    funFact: 'Gar have ganoid scales — diamond-shaped armor plates so hard that Native Americans used them as arrowheads and tools. They\'ve survived virtually unchanged for 100 million years.',
    regulations: { minSize: 'None', dailyLimit: 'None' },
  },
  {
    id: 'yellow-perch',
    name: 'Yellow Perch',
    scientific: 'Perca flavescens',
    aka: ['Perch', 'Ringed Perch', 'Raccoon Perch'],
    category: 'panfish',
    difficulty: 1,
    typicalSize: '0.25–1 lb',
    stateRecord: '2 lb 8 oz',
    fight: 'Mild',
    taste: 'Excellent',
    description: 'A cold-water species at the southern edge of its range in SE Georgia. Less common than bluegill but excellent eating with sweet, flaky meat.',
    habitat: 'Lakes and slow rivers near weed beds and structure. Prefers cooler water.',
    waterTypes: ['lake', 'river', 'pond'],
    bestSeasons: ['fall', 'winter'],
    bestTimes: ['Morning', 'Midday'],
    activeMonths: [10,11,12,1,2,3,4],
    peakMonths: [11,12,1,2],
    diet: 'Insects, larvae, small minnows, crawfish.',
    baits: {
      live: ['Minnows', 'Worms', 'Crickets'],
      artificial: ['Small jigs', 'Tiny spoons'],
    },
    tips: [
      'They\'re a schooling fish — when you catch one, work the area quickly for more',
      'Cooler months are best in Georgia since they\'re a cold-water species at their southern limit',
      'Small minnows under a bobber set at different depths until you locate the school',
      'Light tackle (4–6 lb line) makes them more fun and you\'ll detect more bites',
    ],
    funFact: 'Yellow perch are one of the most widely distributed fish in North America. They\'re the same species behind the famous Lake Erie perch fishery up north.',
    regulations: { minSize: 'None', dailyLimit: '15/day' },
  },
  {
    id: 'american-shad',
    name: 'American Shad',
    scientific: 'Alosa sapidissima',
    aka: ['White Shad', 'Shad'],
    category: 'predator',
    difficulty: 2,
    typicalSize: '2–5 lbs',
    stateRecord: '7 lb 12 oz',
    fight: 'Strong',
    taste: 'Fair',
    description: 'A migratory ocean fish that runs up the Ogeechee River in spring to spawn. They don\'t actually feed during the run but strike out of aggression, making for spectacular light-tackle sport.',
    habitat: 'Ogeechee River and tributaries during spring spawning runs.',
    waterTypes: ['river'],
    bestSeasons: ['spring'],
    bestTimes: ['Morning', 'Evening'],
    activeMonths: [3,4,5],
    peakMonths: [3,4],
    diet: 'Plankton in the ocean. They don\'t feed during the spawning run — strikes are pure aggression.',
    baits: {
      live: [],
      artificial: ['Small shad darts (1/4 oz)', 'Small spoons', 'Jigs in white or chartreuse'],
    },
    tips: [
      'They run up the Ogeechee River in spring — timing is everything, usually March and April',
      'Cast small shad darts across the current and let them swing downstream',
      'They hit hard and jump repeatedly — an absolute blast on ultralight tackle',
      'They don\'t eat during the run, so they strike out of instinct. Bright colors and flash work best.',
    ],
    funFact: 'American shad were so important to early America that George Washington himself was a commercial shad fisherman, and their spring runs helped feed the Continental Army at Valley Forge.',
    regulations: { minSize: 'Check current year', dailyLimit: 'Check GADNR regulations' },
  },
  {
    id: 'red-drum',
    name: 'Red Drum',
    scientific: 'Sciaenops ocellatus',
    aka: ['Redfish', 'Red', 'Puppy Drum', 'Bull Red', 'Channel Bass'],
    category: 'saltwater',
    difficulty: 2,
    typicalSize: '2–10 lbs (slot)',
    stateRecord: '50 lb 5 oz',
    fight: 'Powerful',
    taste: 'Excellent',
    description: 'The iconic inshore saltwater game fish of the Georgia coast. Copper-bronze with a signature black spot near the tail. A day trip from Portal to Savannah puts you in redfish country.',
    habitat: 'Coastal marshes, oyster bars, grass flats, and nearshore waters. Savannah and Tybee area, about 1.5 hours east of Portal.',
    waterTypes: ['marsh', 'flat', 'nearshore'],
    bestSeasons: ['fall'],
    bestTimes: ['Morning', 'Incoming tide'],
    activeMonths: [3,4,5,6,7,8,9,10,11,12],
    peakMonths: [9,10,11],
    diet: 'Shrimp, crabs, mullet, menhaden.',
    baits: {
      live: ['Live shrimp', 'Finger mullet', 'Mud minnows', 'Fiddler crabs'],
      artificial: ['Gold spoons', 'Soft plastic shrimp', 'Topwater plugs', 'Ned rigs'],
      prepared: ['Cut mullet', 'Shrimp pieces'],
    },
    tips: [
      'Look for "tailing" fish in shallow water — their tails stick up as they root on the bottom',
      'Gold spoons are the classic redfish lure — cast past the fish and retrieve steadily',
      'Fish incoming tides around oyster bars and marsh grass edges',
      'Bull reds (20+ lbs) in fall are an unforgettable fight — but release the big ones',
    ],
    funFact: 'The black spot near a redfish\'s tail is thought to be a survival trick — predators attack the spot thinking it\'s an eye, giving the fish a chance to escape in the opposite direction.',
    regulations: { minSize: '14" minimum, 23" maximum (slot)', dailyLimit: '5/day (check current year)' },
  },
  {
    id: 'spotted-seatrout',
    name: 'Spotted Seatrout',
    scientific: 'Cynoscion nebulosus',
    aka: ['Speckled Trout', 'Specks', 'Trout'],
    category: 'saltwater',
    difficulty: 2,
    typicalSize: '1–4 lbs',
    stateRecord: '12 lb 8 oz',
    fight: 'Moderate',
    taste: 'Excellent',
    description: 'The most popular inshore saltwater fish on the Georgia coast. Beautiful silver with black spots. A live shrimp under a popping cork is the most effective setup in Georgia salt water.',
    habitat: 'Grass flats, oyster bars, and nearshore waters. Savannah and Tybee area.',
    waterTypes: ['flat', 'marsh', 'nearshore'],
    bestSeasons: ['spring', 'fall'],
    bestTimes: ['Morning', 'Evening', 'Moving tides'],
    activeMonths: [3,4,5,6,7,8,9,10,11,12],
    peakMonths: [4,5,10,11],
    diet: 'Shrimp, small fish, crabs.',
    baits: {
      live: ['Live shrimp (THE bait)', 'Small finger mullet'],
      artificial: ['DOA shrimp', 'MirrOlures', 'Soft plastics under popping corks', 'Topwater plugs'],
    },
    tips: [
      'A live shrimp under a popping cork is the deadliest setup in Georgia salt water',
      'Pop the cork every few seconds — the noise attracts trout from a distance',
      'Fish grass flats on moving tides, especially near oyster bars',
      'Dawn and dusk topwater action is incredible — the strikes are explosive',
    ],
    funFact: 'Spotted seatrout make a drumming sound during spawning season by vibrating muscles against their swim bladder. On quiet evenings, you can hear them "drumming" from the surface.',
    regulations: { minSize: '14" minimum', dailyLimit: '8/day (check current year)' },
  },
  {
    id: 'flounder',
    name: 'Southern Flounder',
    scientific: 'Paralichthys spp.',
    aka: ['Flatfish', 'Fluke', 'Doormat'],
    category: 'saltwater',
    difficulty: 3,
    typicalSize: '1–5 lbs',
    stateRecord: '18 lb 4 oz',
    fight: 'Moderate',
    taste: 'Excellent',
    description: 'A flat ambush predator that lies on the bottom and waits for prey to pass by. One of the best-eating saltwater fish. The fall flounder run is a highly anticipated event on the Georgia coast.',
    habitat: 'Sandy and muddy bottoms near structure — docks, bridges, jetties, channel edges. Savannah area.',
    waterTypes: ['nearshore', 'flat'],
    bestSeasons: ['fall'],
    bestTimes: ['Incoming tide'],
    activeMonths: [3,4,5,6,7,8,9,10,11],
    peakMonths: [9,10,11],
    diet: 'Finger mullet, shrimp, small fish.',
    baits: {
      live: ['Live finger mullet (#1 bait)', 'Bull minnows', 'Mud minnows', 'Live shrimp'],
      artificial: ['Gulp! swimming mullet', 'Bucktail jigs', 'Soft plastics on jig heads'],
    },
    tips: [
      'Fish slow and on the bottom — flounder are ambush predators that lay flat and wait',
      'Live finger mullet on a Carolina rig dragged slowly is the classic method',
      'The fall flounder run (October–November) is the best time as they migrate offshore to spawn',
      'Look for sandy bottoms near structure — docks, bridge pilings, and channel edges',
    ],
    funFact: 'Flounder are born with eyes on both sides of their head like a normal fish. As they grow, one eye literally migrates across their skull to the other side so both eyes face up when they lie flat.',
    regulations: { minSize: '14" minimum', dailyLimit: '10/day (check current year)' },
  },
  {
    id: 'sheepshead',
    name: 'Sheepshead',
    scientific: 'Archosargus probatocephalus',
    aka: ['Convict Fish', 'Sheepie', 'Prisoner Fish'],
    category: 'saltwater',
    difficulty: 3,
    typicalSize: '1–5 lbs',
    stateRecord: '17 lb 4 oz',
    fight: 'Strong',
    taste: 'Excellent',
    description: 'A notorious bait stealer with black-and-white prison stripes and human-like teeth. One of the best-eating fish in salt water — sweet, firm white meat. Challenging to hook but incredibly rewarding.',
    habitat: 'Docks, pilings, bridges, jetties, oyster beds, and rock walls. Anywhere with barnacles and oysters. Savannah area.',
    waterTypes: ['nearshore', 'structure'],
    bestSeasons: ['winter', 'spring'],
    bestTimes: ['Incoming tide'],
    activeMonths: [11,12,1,2,3,4,5],
    peakMonths: [1,2,3],
    diet: 'Barnacles, oysters, crabs, shrimp, sand fleas.',
    baits: {
      live: ['Fiddler crabs (top bait)', 'Live shrimp', 'Sand fleas', 'Oyster pieces'],
      artificial: ['Small jigs tipped with shrimp (occasionally)'],
    },
    tips: [
      'Fish right against pilings, docks, and jetties — literally within inches of the structure',
      'They\'re the lightest biters in salt water and notorious bait stealers — stay focused',
      'Small, strong hooks (size 1–2) and be ready to set at the slightest tick',
      'Fiddler crabs are the top bait — hook through the back of the shell',
    ],
    funFact: 'Sheepshead have teeth that look almost exactly like human teeth — flat front incisors and rear molars for crushing shells. Looking in their mouth is surprisingly unsettling.',
    regulations: { minSize: 'No minimum (check current year)', dailyLimit: '15/day' },
  },
];

const MONTHS = ['January','February','March','April','May','June','July','August','September','October','November','December'];

const CATEGORY_META = {
  bass:      { label: 'Bass',      color: '#22c55e' },
  catfish:   { label: 'Catfish',   color: '#c8a255' },
  panfish:   { label: 'Panfish',   color: '#f59e0b' },
  predator:  { label: 'Predator',  color: '#ef4444' },
  saltwater: { label: 'Saltwater', color: '#3b82f6' },
};

const DIFFICULTY_LABELS = { 1: 'Beginner', 2: 'Intermediate', 3: 'Advanced' };

const SPECIES_IMAGES = {
  'largemouth-bass': 'img/largemouth-bass.jpg',
  'spotted-bass': 'img/spotted-bass.jpg',
  'channel-catfish': 'img/channel-catfish.jpg',
  'blue-catfish': 'img/blue-catfish.jpg',
  'flathead-catfish': 'img/flathead-catfish.jpg',
  'bullhead-catfish': 'img/bullhead-catfish.jpg',
  'bluegill': 'img/bluegill.jpg',
  'redear-sunfish': 'img/redear-sunfish.jpg',
  'redbreast-sunfish': 'img/redbreast-sunfish.jpg',
  'warmouth': 'img/warmouth.jpg',
  'crappie': 'img/crappie.jpg',
  'chain-pickerel': 'img/chain-pickerel.jpg',
  'bowfin': 'img/bowfin.png',
  'longnose-gar': 'img/longnose-gar.jpg',
  'yellow-perch': 'img/yellow-perch.jpg',
  'american-shad': 'img/american-shad.jpg',
  'red-drum': 'img/red-drum.png',
  'spotted-seatrout': 'img/spotted-seatrout.jpg',
  'flounder': 'img/flounder.gif',
  'sheepshead': 'img/sheepshead.jpg',
};
